spring:
  datasource:
    url: jdbc:mysql://mysql80.wf:3306/test
    username: wf2311
    password: 123456
    hikari:
      allow-pool-suspension: false
      maximum-pool-size: 20
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
