stages:  #这是 Gitlab CI 中的概念，Stages 表示构建阶段，就是一些按序执行的流程，具体执行是依赖于 Jobs 的
  - mvn archetype
maven-archetype:  #定义的 Jobs 之一，用于构建 jar 包。script 为具体执行的脚本
  stage: mvn archetype
  tags:
    - jclipper
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^doc.*$/
  script:
    - mvn clean archetype:create-from-project -Darchetype.properties=archetype.properties
    - cd target/generated-sources/archetype/
    - mv -f src/main/resources/archetype-resources/.gitlab-ci-template.yml src/main/resources/archetype-resources/.gitlab-ci.yml
    - mv -f src/main/resources/archetype-resources/README-template.md src/main/resources/archetype-resources/README.md
    - mvn archetype:crawl
    - mvn clean deploy
