variables:
  # business name, developer define
  BUSINESS_NAME: 'jclipper'
  # project name, developer define
  APP_NAME: 'jclipper-spring-webapp-template'
  # Jar/War path, developer define
  TARGET_PATH: 'target/*.jar'
  # jvm args, developer define
  JVM_OPTS_DEV: '-Xmx512m -Xms512m -Xss512k -Dspring.cloud.nacos.config.namespace=public -Dspring.cloud.nacos.config.server-addr=127.0.0.1:8848'
  JVM_OPTS_TEST1: '-Xmx512m -Xms512m -Xss512k -Dspring.cloud.nacos.config.namespace=public -Dspring.cloud.nacos.config.server-addr=192.168.21.2:8848'
  JVM_OPTS_TEST2: '-Xmx512m -Xms512m -Xss512k -Dspring.cloud.nacos.config.namespace=public -Dspring.cloud.nacos.config.server-addr=192.168.21.3:8848'
  JVM_OPTS_PRE: '-Xmx1024m -Xms1024m -Xss512k -Dspring.cloud.nacos.config.namespace=pre -Dspring.cloud.nacos.config.server-addr=192.168.21.4:8848'
  JVM_OPTS_PROD: '-Xmx1024m -Xms1024m -Xss512k -Dspring.cloud.nacos.config.namespace=prod -Dspring.cloud.nacos.config.server-addr=192.168.21.5:8848'